name: Continuous Integration
on:
  push:
    branches:
      - "main"
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: npm ci
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
    - name: Deploy Serverless
      uses: serverless/github-action@master
      with:
        args: deploy